# Generated by Django 5.2.8 on 2025-11-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='enrolled',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
