# Generated by Django 5.2.8 on 2026-01-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_program_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
