# Generated by Django 5.2.8 on 2026-01-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0003_block_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled',
            field=models.IntegerField(default=0),
        ),
    ]
