# Generated by Django 5.2.8 on 2026-01-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0004_course_enrolled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='capacity',
            new_name='size',
        ),
    ]
