# Generated by Django 6.0.2 on 2026-03-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0006_alter_logentry_options_logentry_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compactness', models.IntegerField(default=80)),
                ('day_balance', models.IntegerField(default=60)),
                ('end_time_preference', models.IntegerField(default=50)),
                ('start_time_preference', models.IntegerField(default=40)),
                ('late_to_early', models.IntegerField(default=90)),
                ('lab_spread', models.IntegerField(default=40)),
                ('days_used', models.IntegerField(default=70)),
            ],
            options={
                'verbose_name': 'Ranking Configuration',
                'verbose_name_plural': 'Ranking Configuration',
            },
        ),
    ]
